### PR TITLE
Make `/od/` redirect to `/od/en/2.0`

### PR DESCRIPTION
**Pull request by jgkim**
I moved the English version of the Open Definition 2.0 to `/od/2.0/en/` somehow fixing https://github.com/okfn/opendefinition/issues/63.

I know we have ugly redirects, but with this commit, we can keep the link to the latest version (`http://opendefinition.org/od/`) intact, and every version remains available at `http://opendefinition.org/od/X.X/` and `http://opendefinition.org/od/X.X/en/`.

### CODE REVIEW

**Comment by jgkim** [comment]
I've noticed there is another discussion about this at: https://github.com/okfn/opendefinition/issues/71.
I agree that redirects with HTTP status codes are the right way to do this, but in the meantime, I think redirecting `/od/` to its current canonical version is a better way to keep the current version at `/od/` in terms of versioning.

**Comment by mlinksva** [comment]
I think I'd rather see an explanatory page linking to the current version than an ugly redirect, but you're right about where the English version should be. I'll look at this again over the weekend, planning to try to get site in order for 2.1.

**Comment by jgkim** [comment]
@mlinksva Any progress on this? Is there anything that I can help with? I'd like to translate the new version of the definition into Korean. When are we ready to update the site for 2.1? It's already officially approved, and if it's possible, I'd like to help you with updating the site for 2.1.

**Comment by mlinksva** [comment]
@jgkim not yet, but I moved 2.1dev to its canonical location, visible now at http://opendefinition.org/od/2.1/en/ ... go ahead with the Korean translation.

**Comment by mlinksva** [comment]
Decided to go ahead with ugly redirect. @hlainchb there are now three things to do when switching the site to 2.1:

* change od_current_version in _config.yml from 2.0 to 2.1
* remove the redirect_from directives from od/2.0/en/index.markdown
* add the same redirect_from directives to od/2.1/en/index.markdown

**Pull request merged**
