### PR TITLE
Rewrite of OFD page

### PR DESCRIPTION
**Pull request by Stephen-Gates**
Partially addresses #93

### CODE REVIEW

**Comment by Stephen-Gates** [comment]
@mlinksva thanks for that. Something got lost with some on the headings ### appears on the published page. Not sure what happened there - any clues on fixing?

**Comment by mlinksva** [comment]
A blank line before each bulleted list and heading was needed.

**Comment by Stephen-Gates** [comment]
Ok thanks @mlinksva - I've spotted some similar issues. Forgive a GItHub newbie - Do I fork the open definition repository again to get the latest OFD page to fix the errors or is there another trick?  Thanks.

**Comment by mlinksva** [comment]
There may be a way to do it in the github UI that I'm not familiar with, but from the command line in your local repository you can do something like

```
git remote add upstream https://github.com/okfn/opendefinition.git
git pull upstream
git push
```

You only need to do the first line once, or maybe not at all -- look at the file .git/config to see if you already have the okfn repo set up as a remote, if so replace upstream with whatever the remote is called.

The second line synchronizes your local repository with this one, the third updates your personal github remote. You can then edit in your account in the github web interface. Or between the pull and push, edit and commit locally. Finally, send a pull request.

**Pull request merged**
