### PR TITLE
Create index.markdown

### PR DESCRIPTION
**Pull request by nikeshbalami**
Creating new index page for Nepal

### CODE REVIEW

**Comment by mlinksva** [comment]
Hi, thanks for this. The title (which should be translated) and `layout: page` (which should not) need to be between ---'s at the top of the file (so-called "front matter"). See https://raw.githubusercontent.com/okfn/opendefinition/gh-pages/od/2.1/en/index.markdown for an example:

```
---
layout: page
title: Open Definition 2.1
---

Version 2.1

The Open Definition makes precise the meaning of "open" with respect to knowledge, promoting a robust commons in which anyone may participate, and interoperability is maximized.

[rest of file skipped]
```

Could you update this pull request with the above change?

**Comment by nikeshbalami** [comment]
Hi, Just made an correction. Is it okay now.

**Comment by mlinksva** [comment]
You still need triple dashes ("---") before and after the layout and title. See the example above.

**Comment by nikeshbalami** [comment]
Hope now it will work, I had changed it according to an example.

**Comment by mlinksva** [comment]
Thanks!

For the links to English Wikipedia, if equivalent articles ever get added to Nepali Wikipedia, feel free and encouraged to make a new pull request substituting in the Nepali ones.

**Comment by nikeshbalami** [comment]
Thank you Mike and sure I will be updating it.

**Pull request merged**
