### PR TITLE
Update open-definition-2.1-dev.markdown

### PR DESCRIPTION
**Pull request by gutam2000**
I have added "interoperable" though the text in the definition gives the similar meaning. But the use of word 'interoperable" is necessary I feel. It is proposed to you for its inclusion.

### CODE REVIEW

**Comment by mlinksva** [comment]
@gutam2000 thanks for the suggestion!

I feel the word interoperable, if it were to be added, needs definition. If "An open format is..." became "An interoperable format is..." how would the rest of the sentence change?

**Comment by Vanuan** [comment]
Well, interoperable doesn't sound very open. For example, binary MS Office formats are "interoperable", but they are not open. This might need further explanation.

**Comment by gutam2000** [comment]
Yes Vanuan you are right. But the point I wanted to make is, it should also be interoperable. The 'Open' should be 'Interoperable'.

**Comment by mlinksva** [comment]
@gutam2000 I still am not sure what interoperable adds here. It needs a precise definition. Do you have one in mind?

**Comment by mlinksva** [comment]
Closing due to lack of precise case for what interoperable adds or means. Feel free to reopen with such a case.

**Pull request closed without merging**
